-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Samsung Display Corp. 0x4154",
  mode = "2880x1800@90.00",
  position = "0x0",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:SKYDATA S.P.A. H24G30Q",
  mode = "2560x1440@120.00",
  position = "1440x0",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
